import { Component } from '@angular/core';
import { StoryDetailsService } from '../service/story.details.service';

@Component({
  selector: 'app-auto-selected-stories',
  templateUrl: './auto-selected-stories.component.html',
  styleUrls: ['./auto-selected-stories.component.css'],
})
export class AutoSelectedStoriesComponent {
  autoSelectedStories! : Array<{ name: string; point: number }>;

  constructor(private storyService: StoryDetailsService) {}

  ngOnInit() {
    this.autoSelectedStories = this.storyService.getAutogeneratedStories();
  }
}
